# Используем официальный образ Python
FROM python:3.10-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir aiogram

# Копируем весь код бота
COPY bot.py .

# Запускаем бота
CMD ["python", "bot.py"]